parameters:
  dependsOnPublishStages: []
  publishingInfraVersion: 3

stages:

# Stages-based publishing entry point
- template: /eng/common/templates/post-build/post-build.yml
  parameters:
    publishingInfraVersion: ${{ parameters.publishingInfraVersion }}
    validateDependsOn:
    - PrepareForPublish
    enableSymbolValidation: false
    enableSigningValidation: false
    enableNugetValidation: false
    enableSourceLinkValidation: false
    publishInstallersAndChecksums: true

    SDLValidationParameters:
      enable: false
      params: >-
        -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL https://devdiv.visualstudio.com/
        -TsaProjectName DEVDIV
        -TsaNotificationEmail wffteam@microsoft.com
        -TsaCodebaseAdmin REDMOND\advolker
        -TsaBugAreaPath "DevDiv\NET Fundamentals\WindowsDesktop"
        -TsaIterationPath DevDiv
        -TsaRepositoryName WindowsDesktop
        -TsaCodebaseName WindowsDesktop
        -TsaOnboard $True
        -TsaPublish $True
