parameters:
  additionalMSBuildArguments: ''
  displayName: ''
  publishRidAgnosticPackages: false
  skipTests: $(SkipTests)
  targetArchitecture: null
  timeoutInMinutes: 120
  disableVSPublish: false

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      # Use a hosted pool when possible.
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: NetCore1ESPool-Svc-Public
        demands: ImageOverride -equals build.windows.10.amd64.vs2019.open
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: NetCore1ESPool-Svc-Internal
        demands: ImageOverride -equals build.windows.10.amd64.vs2019
    strategy:
      matrix: 
        debug:
          _BuildConfig: Debug
        release:
          _BuildConfig: Release
    workspace:
      clean: all
    variables: 
      - name: CommonMSBuildArgs
        value: >-
          /p:Configuration=$(_BuildConfig)
          /p:OfficialBuildId=$(OfficialBuildId)
          /p:TargetArchitecture=${{ parameters.targetArchitecture }}
          /p:PortableBuild=true
          /p:SkipTests=${{ parameters.skipTests }}
      - name: MsbuildSigningArguments
        value: /p:DotNetSignType=$(SignType)
      - name: TargetArchitecture
        value: ${{ parameters.targetArchitecture }}
      - name: DisableVSPublish
        value: ${{ parameters.disableVSPublish }}
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - name: _InternalRuntimeDownloadArgs
          value: ''
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - group: DotNet-MSRC-Storage
        - name: _InternalRuntimeDownloadArgs
          value: >-
            /p:DotNetRuntimeSourceFeed=https://dotnetclimsrc.blob.core.windows.net/dotnet
            /p:DotNetRuntimeSourceFeedKey=$(dotnetclimsrc-read-sas-token-base64)

    steps:
    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: NuGetAuthenticate@0

      - task: PowerShell@2
        displayName: Setup Private Feeds Credentials
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
          arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
        env:
          Token: $(dn-bot-dnceng-artifact-feeds-rw)

      - task: MicroBuildSigningPlugin@2
        displayName: Install MicroBuild plugin for Signing
        inputs:
          signType: $(SignType)
          zipSources: false
          feedSource: https://dnceng.pkgs.visualstudio.com/_packaging/MicroBuildToolset/nuget/v3/index.json
        continueOnError: false
        condition: and(succeeded(), 
                       in(variables['SignType'], 'real', 'test'))
    # NuGet's http cache lasts 30 minutes. If we're on a static machine, this may interfere with
    # auto-update PRs by preventing the CI build from fetching the new version. Delete the cache.
    - powershell: Remove-Item -Recurse -ErrorAction Ignore "$env:LocalAppData\NuGet\v3-cache"
      displayName: Clear NuGet http cache (if exists)

    - script: >-
        build.cmd -ci -test
        $(CommonMSBuildArgs)
        $(MsbuildSigningArguments)
        $(_InternalRuntimeDownloadArgs)
      displayName: Build

    # Generate SBOM for the internal leg only
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - template: ..\common\templates\steps\generate-sbom.yml
        parameters:
          name: Generate_SBOM_${{ parameters.name }}

    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - task: NuGetCommand@2
        displayName: Push Visual Studio NuPkgs
        inputs:
          command: push
          packagesToPush: '$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/*/VS.Redist.Common.*.nupkg'
          nuGetFeedType: external
          publishFeedCredentials: 'DevDiv - VS package feed'
        condition: and(
          succeeded(),
          eq(variables['_BuildConfig'], 'Release'),
          ne(variables['DisableVSPublish'], 'true'),
          ne(variables['PostBuildSign'], 'true'))

    - template: steps/upload-job-artifacts.yml
      parameters:
        name: ${{ parameters.name }}
