parameters:
  dependsOn: []
  PublishRidAgnosticPackagesFromJobName: ''

jobs:
- job: PrepareSignedArtifacts
  displayName: Prepare Signed Artifacts
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals windows.vs2019.amd64
  # Double the default timeout.
  timeoutInMinutes: 120
  workspace:
    clean: all

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download IntermediateUnsignedArtifacts
    inputs:
      artifactName: IntermediateUnsignedArtifacts
      downloadPath: $(Build.SourcesDirectory)\artifacts\PackageDownload

  - script: >
      build.cmd -ci
      -projects $(Build.SourcesDirectory)\src\publish\prepare-artifacts.proj
      -c Release
      /p:PublishRidAgnosticPackagesFromJobName=${{ parameters.PublishRidAgnosticPackagesFromJobName }}
      /p:SignType=$(SignType)
      /p:DotNetSignType=$(SignType)
      /bl:$(Build.SourcesDirectory)\prepare-artifacts.binlog
    displayName: Prepare artifacts and upload to build

  - task: CopyFiles@2
    displayName: Copy Files to $(Build.StagingDirectory)\BuildLogs
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*.log
        **/*.binlog
      TargetFolder: '$(Build.StagingDirectory)\BuildLogs'
    continueOnError: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact BuildLogs
    inputs:
      PathtoPublish: '$(Build.StagingDirectory)\BuildLogs'
      ArtifactName: Logs-PrepareSignedArtifacts
    condition: succeededOrFailed()