parameters:
  additionalMSBuildArguments: ''
  displayName: ''
  skipTests: $(SkipTests)
  targetArchitecture: null
  timeoutInMinutes: 120

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      # Use a hosted pool when possible.
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        vmImage: 'windows-2022'
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: NetCore1ESPool-Internal
        demands: ImageOverride -equals windows.vs2019.amd64
    strategy:
      matrix: 
        Debug:
          _BuildConfig: Debug
        Release:
          _BuildConfig: Release
    workspace:
      clean: all
    variables: 
      - name: CommonMSBuildArgs
        value: >-
          -c $(_BuildConfig)
          /p:TargetArchitecture=${{ parameters.targetArchitecture }}
          /p:SkipTests=${{ parameters.skipTests }}
      - name: TargetArchitecture
        value: ${{ parameters.targetArchitecture }}
      - ${{ if eq(variables['System.TeamProject'], 'public') }}:
        - name: MsbuildSigningArguments
          value: /p:DotNetSignType=Test
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - name: MsbuildSigningArguments
          value: /p:DotNetSignType=Real

    steps:
    - template: /eng/common/templates/steps/enable-internal-sources.yml

    # Download runtime MSI artifacts from the runtime build
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Runtime MSI Artifacts'
      inputs:
        buildType: 'specific'
        project: 'internal'
        pipeline: 'dotnet-runtime-official'
        buildVersionToDownload: 'latestFromBranch'
        branchName: 'refs/heads/main'
        artifactName: 'PackageArtifacts'
        itemPattern: |
          **/**/dotnet-host-*-win-${{ parameters.targetArchitecture }}.msi
          **/**/dotnet-hostfxr-*-win-${{ parameters.targetArchitecture }}.msi
          **/**/dotnet-runtime-*-win-${{ parameters.targetArchitecture }}.msi
        downloadPath: '$(Build.SourcesDirectory)/artifacts/runtime-msis'
      condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'))

    # Copy MSIs to expected location for bundle build
    - task: CopyFiles@2
      displayName: 'Stage Runtime MSIs for Bundle'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/runtime-msis'
        Contents: '**/*.msi'
        TargetFolder: '$(Build.SourcesDirectory)/artifacts/packages/$(_BuildConfig)/Shipping'
        flattenFolders: true
      condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'))

    - ${{ if ne(variables['System.TeamProject'], 'public') }}:
      - task: MicroBuildSigningPlugin@4
        displayName: Install MicroBuild plugin for Signing
        inputs:
          signType: $(SignType)
          zipSources: false
          feedSource: https://dnceng.pkgs.visualstudio.com/_packaging/MicroBuildToolset/nuget/v3/index.json
        continueOnError: false
        condition: and(succeeded(), in(variables['SignType'], 'real', 'test'))

    - script: >-
        eng/common/cibuild.cmd
        $(CommonMSBuildArgs)
        $(MsbuildSigningArguments)
      displayName: Build

    - ${{ if ne(parameters.skipTests, 'true') }}:
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: 'xUnit'
          testResultsFiles: '*.xml'
          searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)'
          mergeTestResults: true
          testRunTitle: ${{ parameters.name }}-$(_BuildConfig)
        continueOnError: true
        condition: always()

    - task: CopyFiles@2
      displayName: Prepare BuildLogs staging directory
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.log
          **/*.binlog
        TargetFolder: '$(Build.StagingDirectory)/BuildLogs'
        CleanTargetFolder: true
      continueOnError: true
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: Publish BuildLogs
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)/BuildLogs'
        ArtifactName: Logs-${{ parameters.name }}-$(_BuildConfig)
      continueOnError: true
      condition: succeededOrFailed()
