name: PR unblock - windowsdesktop-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  windowsdesktop-pr:
    name: windowsdesktop-pr
    runs-on: ubuntu-latest
    steps:
      - name: No-op - satisfy branch protection
        run: |
          echo "This workflow only exists to provide a temporary status check named 'windowsdesktop-pr' for branch-protection unblocking."
          echo "If you see this, the fallback Action worked."
